CC = gcc
OBJECTS = rp_main.o ../mr_common.o rp_timer.o rp_fhr.o

routingp: $(OBJECTS)
	$(CC) -o routingp $(OBJECTS) -lpthread

rp_main.o: rp_main.c rp_common.h
	$(CC) -c rp_main.c

mr_commom.o: ../mr_common.c ../mr_common.h
	$(CC) -c ../mr_common.c

rp_timer.o: rp_timer.c rp_timer.h ../mr_common.h
	$(CC) -c rp_timer.c

rp_fhr.o: rp_fhr.c rp_fhr.h ../mr_common.h
	$(CC) -c rp_fhr.c

clean :
	rm $(OBJECTS) 
